#--------------------------------------------------
# Bash initialization
#--------------------------------------------------
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac


#--------------------------------------------------
# History configuration
#--------------------------------------------------
# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# history length
export HISTCONTROL=ignoredups:erasedups
HISTSIZE=10000
HISTFILESIZE=20000


#--------------------------------------------------
# Default editor
#--------------------------------------------------
export EDITOR=vim


#--------------------------------------------------
# Default permissions
#--------------------------------------------------
# Sets default file permissions for new files and directories
umask 022


#--------------------------------------------------
# Shell behavior
#--------------------------------------------------
# update LINES and COLUMNS automatically
shopt -s checkwinsize

# enable recursive globbing (**)
# shopt -s globstar


#--------------------------------------------------
# less configuration
#--------------------------------------------------
# make less more friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"


#--------------------------------------------------
# Debian chroot detection
#--------------------------------------------------
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi


#--------------------------------------------------
# Prompt configuration
#--------------------------------------------------
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        color_prompt=yes
    else
        color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi

unset color_prompt force_color_prompt


#--------------------------------------------------
# Xterm title
#--------------------------------------------------
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac


#--------------------------------------------------
# Color support and core aliases
#--------------------------------------------------
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


#--------------------------------------------------
# Useful ls aliases
#--------------------------------------------------
alias ll='ls -alF'
alias la='ls -A'
alias lsmore='ls -alth --color=auto | more'


#--------------------------------------------------
# Notification helper
#--------------------------------------------------
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


#--------------------------------------------------
# Additional user aliases
#--------------------------------------------------
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


#--------------------------------------------------
# Bash completion
#--------------------------------------------------
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


#--------------------------------------------------
# Custom system prompt
#--------------------------------------------------
PS1='[\u@\h \W]\$ '


#--------------------------------------------------
# Custom utilities
#--------------------------------------------------
source /home/lochy/Desktop/usrbin/enable.sh


#--------------------------------------------------
# Conda configuration
#--------------------------------------------------
/home/lochy/anaconda3/bin/conda config --set auto_activate_base False

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/lochy/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/lochy/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/lochy/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/lochy/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


#--------------------------------------------------
# ASPECT library environment
#--------------------------------------------------
source /home/lochy/ASPECT_PROJECT/aspectLib/enable.sh
source /home/lochy/ASPECT_PROJECT/aspectLib/env/enable_ucd.sh
alias lab='cd $ASPECT_LAB_DIR'


#--------------------------------------------------
# ASPECT source
#--------------------------------------------------
export ASPECT_SOURCE_DIR=/home/lochy/Softwares/aspect
alias aspect='cd $ASPECT_SOURCE_DIR'
alias sq='ps -axu | grep aspect'


#--------------------------------------------------
# HaMaGeoLib
#--------------------------------------------------
export HaMaGeoLib_DIR=/home/lochy/ASPECT_PROJECT/HaMaGeoLib
alias hama='cd $HaMaGeoLib_DIR && source /home/lochy/anaconda3/bin/activate hmgeolib'


#--------------------------------------------------
# WorldBuilder
#--------------------------------------------------
export WORLD_BUILDER_SOURCE_DIR=/home/lochy/Softwares/WorldBuilder


#--------------------------------------------------
# Visit
#--------------------------------------------------
export PATH=$PATH:/home/lochy/Softwares/visit/bin


#--------------------------------------------------
# Work directories
#--------------------------------------------------
alias twod='cd $TwoDSubduction_DIR'
alias thd='cd $ThDSubduction_DIR'

export ThDSubduction_backup_DIR="/mnt/lochy2/ASPECT_DATA/ThDSubduction"
alias thd1='cd $ThDSubduction_backup_DIR'

export MOW="/mnt/lochy/ASPECT_DATA/MOW"
export MOW_HIVE="/quobyte/billengrp/lochy/MOW"
alias mow="cd $MOW"


#--------------------------------------------------
# Developer tools
#--------------------------------------------------
# astyle
export PATH=$PATH:/home/lochy/Softwares/astyle/build/gcc/bin

# blender
export PATH=$PATH:/home/lochy/Softwares/blender-3.2.1-linux-x64


#--------------------------------------------------
# ParaView
#--------------------------------------------------
export PV_INTERFACE_PATH=/home/lochy/Softwares/ParaView-5.11.2-MPI-Linux-Python3.9-x86_64/plugins/SCM8


# -----------------------------
# Project collision
# -----------------------------
export COLLISION="/mnt/lochy/ASPECT_DATA/Collision0"
export COLLISION_HIVE="/quobyte/billengrp/lochy/Collision0"
alias collision="cd $COLLISION"


# -----------------------------
# Multi-Project Commands
# -----------------------------
export PROJECT="${MOW}:${COLLISION}"
export PROJECT_HIVE="${MOW_HIVE}:${COLLISION_HIVE}"

alias from_hive="${HaMaGeoLib_DIR}/scripts/bash_scripts/from_hive.sh"
alias to_hive="${HaMaGeoLib_DIR}/scripts/bash_scripts/to_hive.sh"
