# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend


#Sets the default text editor** to `vim`
export EDITOR=vim

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTCONTROL=ignoredups:erasedups
HISTSIZE=10000
HISTFILESIZE=20000

# Sets default file permissions for new files and directories
umask 022

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias lsmore='ls -alth --color=auto | more'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# system prompt
PS1='[\u@\h \W]\$ '

# usrbin
source /home/lochy/Desktop/usrbin/enable.sh

/home/lochy/anaconda3/bin/conda config --set auto_activate_base False
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/lochy/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/lochy/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/lochy/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/lochy/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# aspectLib
source /home/lochy/ASPECT_PROJECT/aspectLib/enable.sh
source /home/lochy/ASPECT_PROJECT/aspectLib/env/enable_ucd.sh
alias lab='cd $ASPECT_LAB_DIR'

# aspect
export ASPECT_SOURCE_DIR=/home/lochy/Softwares/aspect
alias aspect='cd $ASPECT_SOURCE_DIR'
alias sq='ps -axu | grep aspect'

# Hamageolib
export HaMaGeoLib_DIR=/home/lochy/ASPECT_PROJECT/HaMaGeoLib
alias hama='cd $HaMaGeoLib_DIR'

# world builder
export WORLD_BUILDER_SOURCE_DIR=/home/lochy/Softwares/WorldBuilder

# visit
export PATH=$PATH:/home/lochy/Softwares/visit/bin

# work directories
alias twod='cd $TwoDSubduction_DIR'
alias thd='cd $ThDSubduction_DIR'
export ThDSubduction_backup_DIR="/mnt/lochy2/ASPECT_DATA/ThDSubduction"
alias thd1='cd $ThDSubduction_backup_DIR'
export MOW_DIR="/mnt/lochy/ASPECT_DATA/MOW"
alias mow="cd $MOW_DIR"

# astyle
export PATH=$PATH:/home/lochy/Softwares/astyle/build/gcc/bin

# blender
export PATH=$PATH:/home/lochy/Softwares/blender-3.2.1-linux-x64

# paraview
export PV_INTERFACE_PATH=/home/lochy/Softwares/ParaView-5.11.2-MPI-Linux-Python3.9-x86_64/plugins/SCM8
