#
# GMT 6.6.0 Defaults file
#
# FONT Parameters
#
FONT_ANNOT_PRIMARY             = 10p,Helvetica,black
FONT_ANNOT_SECONDARY           = 10p,Helvetica,black
FONT_LABEL                     = 10p,Helvetica,black
FONT_TITLE                     = 10p,Helvetica,black
#
# FORMAT Parameters
#
FORMAT_GEO_MAP                 = +D
#
# MAP Parameters
#
MAP_ANNOT_OFFSET_PRIMARY       = 2p
MAP_FRAME_TYPE                 = plain
MAP_GRID_PEN_PRIMARY           = thinner,gray74
MAP_LABEL_OFFSET               = 2p
MAP_TICK_LENGTH_PRIMARY        = 0.05i/0.025i
MAP_TITLE_OFFSET               = 2p
#
# Projection Parameters
#
PROJ_LENGTH_UNIT               = inch
#
# PostScript Parameters
#
PS_MEDIA                       = letter
